#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai

uci set network.lan.ipaddr='10.0.0.1'
uci set network.lan.netmask='255.255.255.0'
#uci set network.lan.gateway='192.168.2.1'
uci set network.lan.broadcast='10.0.0.255'
uci set network.lan.dns='119.29.29.29 223.5.5.5'
uci set network.lan.delegate='0'
uci commit network

